cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'caskroom/versions'

brew 'node'
brew 'findutils'
brew 'openssl'
brew 'nvm'
brew 'httpie'
brew 'git'

cask 'alfred'
cask 'iterm2'
cask 'zsh'
cask 'skype'
cask 'spectacle'
cask 'visual-studio-code'
cask 'macvim'
cask 'google-chrome'
cask 'slack'
cask 'vlc'
cask 'spectacle'
cask 'caffeine'
cask 'sqlectron'
cask 'spotify'
cask 'postman'